# render.yaml

databases:
  - name: movie_theater_db
    plan: free
    databaseName: movie_theater_booking
    user: movie_theater_user

services:
  - type: web
    plan: free
    name: movie_theater_booking
    runtime: python
    buildCommand: 'pip install -r requirements.txt'
    startCommand: 'gunicorn movie_theater_booking.wsgi:application'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: movie_theater_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: '.onrender.com'
